swagger: "2.0"
info:
  title: Hello Express API
  description: API description for the Hello World app.
  version: 1.0.0
basePath: /
schemes:
  - http
paths:
  /:
    get:
      summary: Returns just a hello text.
      produces:
        - text/plain
      responses:
        200:
          description: OK
  /404:
    get:
      summary: This should not be found.
      produces:
        - text/plain
      responses:
        200:
          description: OK
  /boom:
    get:
      summary: Do something silly.
      produces:
        - text/plain
      responses:
        200:
          description: OK